### ISSUE TITLE
Using custom serverURL in gui is not working

### ISSUE THREAD

**Issue by wirthual** [lennhv/jitsi_meet_plugin#3]
I tried to add the path meeting.vm.uni-freiburg.de in the GUI but it seems I was still connecting to meet.jit.si

**Comment by lennhv** [comment]
Hi @wirthual sorry for the late, thanks for de bug report the bug was fixed, i test with your domain and the conferencing was launched successfully. Please, test it.

**Comment by wirthual** [comment]
I tested it with a custom URL and can confirm its working. Thanks for the fast fix.
