### ISSUE TITLE
Getting error when we are adding reposestry

### ISSUE THREAD

**Issue by chilakam-dinesh-reddy** [lennhv/jitsi_meet_plugin#4]
Could not find a file named "jitsi_meet_plugin/jitsi_meet_web/pubspec.yaml" in git://github.com/lennhv/jitsi_meet_plugin.git 1f2b36bac16ec4db37fb213d894c4a8771f82249.

**Comment by chilakam-dinesh-reddy** [comment]
This way a i am adding in pubspace.yml


  jitsi_meet_web:
    git:
      url: git://github.com/lennhv/jitsi_meet_plugin.git
      path: jitsi_meet_plugin/jitsi_meet_web

**Comment by lennhv** [comment]
Hi @chilakam-dinesh-reddy  i added the instructions for use the code in a project. Please review it and let me know if work for you.

**Comment by chilakam-dinesh-reddy** [comment]
yes @lennhv  it totally working fine   tq u so much
